// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsFCIx_Juk_e1zDzNXmBlV0dt4mLvPp_g',
    appId: '1:244960643470:web:b4ce9921aec8e9740a3cdf',
    messagingSenderId: '244960643470',
    projectId: 'appjam-1',
    authDomain: 'appjam-1.firebaseapp.com',
    storageBucket: 'appjam-1.appspot.com',
    measurementId: 'G-JXG6D7VHD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs5hOA2TDEC3OUsVJiOgYC4J97znbeQco',
    appId: '1:244960643470:android:7d99791c0d6d9f130a3cdf',
    messagingSenderId: '244960643470',
    projectId: 'appjam-1',
    storageBucket: 'appjam-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKX2uOQBMGG7Lb65tQMDl6A3wXk7iKu2g',
    appId: '1:244960643470:ios:88bfd2dc37cb0c7c0a3cdf',
    messagingSenderId: '244960643470',
    projectId: 'appjam-1',
    storageBucket: 'appjam-1.appspot.com',
    iosBundleId: 'com.example.appjam1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKX2uOQBMGG7Lb65tQMDl6A3wXk7iKu2g',
    appId: '1:244960643470:ios:67bed0380354b2f30a3cdf',
    messagingSenderId: '244960643470',
    projectId: 'appjam-1',
    storageBucket: 'appjam-1.appspot.com',
    iosBundleId: 'com.example.appjam1.RunnerTests',
  );
}
